# Generated by Django 4.1.1 on 2022-10-21 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=50, null=True)),
                ('answer', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('numberQuestions', models.IntegerField(blank=True, default=0, null=True)),
                ('attachImage', models.FileField(upload_to='media/coverPhoto/attachImage')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('cashReward', models.BooleanField(default=False)),
                ('physicalReward', models.BooleanField(default=False)),
                ('select_winner', models.IntegerField(blank=True, default=1, null=True)),
                ('cashPrize', models.BigIntegerField(blank=True, default=0, null=True)),
                ('worth', models.BigIntegerField(blank=True, default=0, null=True)),
                ('otherBenefit', models.CharField(blank=True, max_length=500, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('payin', models.BooleanField(default=False)),
                ('payout', models.BooleanField(default=False)),
                ('payoutFailed', models.BooleanField(default=False)),
                ('payinFailed', models.BooleanField(default=False)),
                ('questions', models.ManyToManyField(blank=True, related_name='quiz_question', to='Quiz.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quiz_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
