# Generated by Django 4.1.1 on 2022-10-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challenge', '0002_challenge_active_challenge_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='minimumVote',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='voter',
            field=models.CharField(choices=[('public', 'public'), ('followers', 'followers'), ('selected', 'selected')], default='public', max_length=150),
        ),
    ]
