# Generated by Django 4.1.1 on 2022-10-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challenge', '0004_challenge_eight_place_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='ninth_place_reward',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
